config/routes.rb
Rails.application.routes.draw do
  get 'order/index'
  get 'order/show'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :genres, only: %i[index show]
  resources :books, only: %i[index show search list_new list_recent_update] do
    collection do
      get :search, :list_new, :list_recent_update
    end
  end
  resources :cart, only: %i[index create destroy update]

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  root to: "books#index"
end

app/models/book.rb
class Book < ApplicationRecord
  paginates_per 9
  belongs_to :genre

  has_many :ordered_books, dependent: :destroy
  has_many :orders, through: :ordered_books

  validates :title, :price, :author, :publisher, presence: true
  validates :price, numericality: true
  has_one_attached :image
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.page(params[:page])
  end

  # GET /books/:id
  def show
    @book = Book.find(params[:id])
  end

  def search
    @key_word = params[:keyword]
    @category_id = params[:name].to_i
    @category_name = Genre.find(params[:name]).name

    @books = if @key_word.blank?
               if @category_name == "all"
                 Book.all.page(params[:page])
               else
                 Book.where("genre_id == :cat", cat: @category_id)
                     .page(params[:page])
               end
             elsif @category_name == "all"
               Book.where("title LIKE ? OR description LIKE ?", "%#{@key_word}%", "%#{@key_word}%")
                   .page(params[:page])
             else
               Book.where("title LIKE ? OR description LIKE ?", "%#{@key_word}%", "%#{@key_word}%")
                   .where("genre_id == :cat", cat: @category_id)
                   .page(params[:page])
             end
  end

  def list_new
    @books = Book.where("created_at >= ?", 2.days.ago).page(params[:page])
  end

  def list_recent_update
    @books = Book.where("created_at <= ?", 2.days.ago)
                 .where("updated_at >= ?", 2.days.ago).page(params[:page])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <p class="title">
        <% if show_link %>
          <%= link_to book.title, book %>
        <% else %>
          <%= book.title %>
        <% end %>
      </p>
      <p>Price: <%= number_to_currency book.price / 100.0 %></p>
    </div>


      <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, book.id)%>
        <%= button_tag 'Add to Cart'%>
      <% end %>

      <% if cart.include?(book) %>
        <%= button_to cart_path(book), method: :delete do %>
          Remove From Cart
        <% end %>
      <% end %>


    <footer class="card-footer">
      <p class="card-footer-item">
        Author: <br><%= book.author %>
      </p>
      <p class="card-footer-item">
        Publisher: <br><%= book.publisher %>
      </p>
      <p class="card-footer-item">Genre: <%= link_to book.genre.name, book.genre %></p>

    </footer>
  </div>

</div>

app/views/books/_search.html.erb
<div class="d-flex bd-highlight">

  <div class="p-2 flex-grow-1 bd-highlight">
    <%= form_with(url:search_books_path, local:true, method:"get", class:'form-inline my-2 my-lg-0') do |f|%>
      By Category: <%= f.select :name, options_from_collection_for_select(Genre.all, :id, :name)%>
    <%= text_field_tag :keyword %>
    <%= submit_tag ("Search")%>
    <% end %>
  </div>

  <div class="p-2 bd-highlight">
    <%= link_to "New Books", list_new_books_path, :class => 'btn btn-success'%>
  </div>

  <div class="p-2 bd-highlight">
    <%= link_to "Recently Updated", list_recent_update_books_path, :class => 'btn btn-success'%>
  </div>

</div>

app/views/books/index.html.erb
<h3 class="title is-4">All Books</h3>


<div class="columns is-multiline">
  <%= render partial: 'books/book',
              collection: @books,
              locals: { show_link: true }%>
</div>


<div class="row"> <%= paginate @books%> </div>

app/views/books/list_new.html.erb
<h3 class="title is-4">New Books</h3>

<div class="columns is-multiline">
  <%= render partial: 'books/book',
              collection: @books,
              locals: { show_link: true }%>
  <% if @books.count == 0 %>
    <p>No results found!</p>
  <% end %>
</div>


<div class="row"> <%= paginate @books%> </div>

app/views/books/list_recent_update.html.erb
<h3 class="title is-4">Recently Updated Books</h3>

<div class="columns is-multiline">
  <%= render partial: 'books/book',
              collection: @books,
              locals: { show_link: true }%>
  <% if @books.count == 0 %>
    <p>No results found!</p>
  <% end %>
</div>


<div class="row"> <%= paginate @books%> </div>

app/views/books/search.html.erb
<h3 class="title is-4">Search Result</h3>

<div class="columns is-multiline">
  <%= render partial: 'books/book',
              collection: @books,
              locals: { show_link: true }%>
  <% if @books.count == 0 %>
    <p>No results found!</p>
  <% end %>
</div>


<div class="row"> <%= paginate @books%> </div>

app/views/books/show.html.erb
<div class="columns">
  <%= render partial: 'book',
             object: @book,
             locals: { show_link: true } %>
</div>